# Generated by Django 3.2.2 on 2021-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210509_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avalaible',
            field=models.BooleanField(default=True),
        ),
    ]
