# Generated by Django 3.2.2 on 2021-05-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_avalaible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avalaible',
            new_name='available',
        ),
    ]
