# Generated by Django 3.2.2 on 2021-05-11 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
